### ISSUE TITLE
Support .jshintignore files

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-jshint#22] opened 2016-04-22 23:24 UTC
We should respect .jshintignore files as described in http://jshint.com/docs/cli/

**Comment by kieferrm** [comment] 2016-04-26 05:17
Started development in https://github.com/Microsoft/vscode-jshint/tree/feature/jshintignore.

**Comment by kieferrm** [comment] 2016-05-04 01:54
Closed with https://github.com/Microsoft/vscode-jshint/commit/49b92580dbb728b36e8613834d74b98068f9a247.

**Comment by baelter** [comment] 2018-03-21 08:01
Can't get this to work,

Putting 
```
**/*
```

in `.jshintignore` and all files are linted.

vscode: 1.21.1
vscode-jshint: 0.10.17
jshint: 2.9.5

**Comment by RMacfarlane** [comment] 2018-06-04 22:11
@baelter @osya Thanks for reporting and the clear steps to reproduce! There was an issue with caching that I just checked in a fix for. The extension maintains a cache for excludes that was correctly being cleared, but there was also a cache being maintained by a parsing library that wasn't cleared. I'll publish a new version of the extension soon.

**Closed by RMacfarlane** 2018-06-04 22:11 UTC
Labels: feature-request

**Comment by RMacfarlane** [comment] 2018-06-07 22:03
@baelter @osya Just published a new version of the extension. Please give it a try

**Comment by osya** [comment] 2018-06-10 15:20
@RMacfarlane , thank you for your attention. I just checked. But the issue still exists.

vscode: 1.24.0
vscode-jshint: 0.10.19
jshint: 2.9.5

**Comment by RMacfarlane** [comment] 2018-06-11 17:12
@osya Hmm, I've tried your steps above with the versions you listed and it works for me. Could you share your settings?

**Comment by osya** [comment] 2018-06-12 07:39
@RMacfarlane , sorry. It works. I just added the content `**/*.jsx` to the file `.jshintignore` and then `jshint` begins ignoring *.jsx files. Empty file `.jshintignore` with the user setting 
```
"jshint.exclude": {
    "**/*.jsx": true
},
```
does not ignore *.jsx files. It seems it is correct
