### ISSUE TITLE
Frequently getting warnings even if the code formatting is perfect.

### ISSUE THREAD

**Issue by codemilan** [Microsoft/vscode-jshint#55] opened 2018-03-25 06:23 UTC
I simple created react app using 'create-react-app' command generating default boilerplate code, but the linter gives below warning message for below mentioned code below warning message :

[jshint] Unclosed regular expression. (E015)
[jshint] Unrecoverable syntax error. (50% scanned). (E041)

```jsx
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1> // warning is here underlined in </h1> closing tag.
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
      </div>
    );
  }
}

export default App;

**Comment by RMacfarlane** [comment] 2018-03-26 02:49
Thanks for reporting! I think this is a duplicate of https://github.com/Microsoft/vscode-jshint/issues/29.  JSHint doesn't recognize the jsx syntax of the return statement. One workaround for now would be to add `/* jshint ignore:start */` before the return and `/* jshint ignore:end */` after the end of the return.

Closing this as a duplicate.

**Closed by RMacfarlane** 2018-03-26 02:49 UTC

**Comment by lionroy** [comment] 2018-07-25 07:41
@RMacfarlane  'One workaround for now would be to add /* jshint ignore:start */ before the return and /* jshint ignore:end */ after the end of the return.;
  ---> add it where ? and why this code is commented out?
ty

**Comment by nycat** [comment] 2019-03-29 00:46
Any elegant solution? I think this solution quite dummy as you need to add this code segment at every render function.
