### ISSUE TITLE
Enable only when .jshintrc is present

### ISSUE THREAD

**Issue by ypresto** [Microsoft/vscode-jshint#42] opened 2017-01-04 11:58 UTC
I'm using vscode for various project, and only a few projects have jshintrc and others have eslintrc.
I want to enable this plugin only when `.jshintrc` is present because it shows many error for es6 syntaxes by default, even the project is checked by eslint.

There is vscode issue for enabling plugin per project but is in Backlog.
https://github.com/Microsoft/vscode/issues/15611

**Comment by entozoon** [comment] 2017-12-07 16:33
+1
It's dang annoying that it kicks in by default; inescapably

**Comment by RMacfarlane** [comment] 2018-01-19 00:36
Closing as duplicate of Microsoft/vscode-jshint/issues/39
Also, the ability to enable extensions only for specific workspaces has shipped in VSCode :tada:

**Closed by RMacfarlane** 2018-01-19 00:36 UTC

**Comment by entozoon** [comment] 2018-01-19 09:15
That's not an ideal solution.
